### ISSUE TITLE
Online demo and downloaded application are not working

### ISSUE THREAD

**Issue by mortezasoft** [kriasoft/AngularJS-SPA-Template#8]
Online demo and downloaded application are not working. There is an error I think relevant to the upgraded version for routing.

**Comment by koistya** [comment]
http://angular-demo.tarkus.me - works for me:

![angular-demo](http://i.imgur.com/COr9mh1.gif)

@mortezasoft can you please clarify what exactly is not working on the demo site?

**Comment by mortezasoft** [comment]
You are right, online demo is working but when I open the project with VS2013 and run it, nothing is working and this is the log in console:
![spa](https://f.cloud.github.com/assets/876408/2243715/2ced688c-9d32-11e3-83fc-3437de8d497c.png)

And this is the link in AngularJS website:
http://docs.angularjs.org/error/$injector/modulerr?p0=app&p1=Error:%20%5B$injector:nomod%5D%20http:%2F%2Ferrors.angularjs.org%2F1.2.3%2F$injector%2Fnomod%3Fp0%3Dapp%0A%20%20%20%20at%20Error%20(native)%0A%20%20%20%20at%20http:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.3%2Fangular.min.js:6:449%0A%20%20%20%20at%20http:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.3%2Fangular.min.js:20:165%0A%20%20%20%20at%20http:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.3%2Fangular.min.js:21:170%0A%20%20%20%20at%20http:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.3%2Fangular.min.js:28:434%0A%20%20%20%20at%20Array.forEach%20(native)%0A%20%20%20%20at%20q%20(http:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.3%2Fangular.min.js:7:255)%0A%20%20%20%20at%20e%20(http:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.3%2Fangular.min.js:28:374)%0A%20%20%20%20at%20Yb%20(http:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.3%2Fangular.min.js:32:427)%0A%20%20%20%20at%20Xb.c%20(http:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.3%2Fangular.min.js:17:315

Am I doing something wrong?

**Comment by koistya** [comment]
Click on the `Network` tab in Chrome DevTools and check if all the external resources referenced on the page were loaded (or are there any 404 errors).

**Comment by mortezasoft** [comment]
It seems all is well here but I still see the error.
![spa2](https://f.cloud.github.com/assets/876408/2244487/674b597e-9d3e-11e3-9a81-652491718ae0.png)
